// Mock data for activities
export const mockActivities = {
    'tours-and-experiences': {
        title: 'Tours & Experiences',
        activities: [
            {
                id: 1,
                slug: 'baan-farm-thai-cooking-school',
                title: 'Baan Farm Thai Cooking School',
                image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&h=300&fit=crop&crop=center',
                rating: 4.9,
                reviews: 235,
                bookings: '3K+',
                price: 24.79,
                originalPrice: 30.99,
                discount: 20,
                location: 'Bangkok',
                duration: '4 hours',
                guide: 'English guide',
                category: 'luxury',
                description: 'Learn authentic Thai cooking techniques in a traditional farm setting',
                availableDates: [new Date(2025, 6, 28), new Date(2025, 6, 29)],
            },
            {
                id: 2,
                slug: 'phi-phi-islands-speedboat-tour',
                title: 'Phi Phi Islands Speedboat Tour',
                image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=400&h=300&fit=crop&crop=center',
                rating: 4.7,
                reviews: 892,
                price: 45.5,
                originalPrice: 55.0,
                discount: 17,
                location: 'Phuket',
                duration: '8 hours',
                guide: 'Multi-language guide',
                category: 'midrange',
                description: 'Explore the stunning Phi Phi Islands with snorkeling and beach visits',
                availableDates: [new Date(2025, 6, 28), new Date(2025, 6, 30)],
            },
            {
                id: 3,
                slug: "chiang-mai-elephant-sanctuary",
                title: 'Bangkok Hop-On Hop-Off Bus',
                image: '/images/hop-on.jpg',
                rating: 4.3,
                reviews: 456,
                price: 15.99,
                location: 'Bangkok',
                duration: '24 hours',
                guide: 'Audio guide',
                category: 'budget',
                description: "Discover Bangkok's top attractions at your own pace",
                availableDates: [new Date(2025, 6, 28), new Date(2025, 6, 29)],
            },
            {
                id: 4,
                slug: "bangkok-temple-cultural-tour",
                title: 'Chiang Mai Mountain Hiking Adventure',
                image: 'https://images.unsplash.com/photo-1551632811-561732d1e306?w=400&h=300&fit=crop&crop=center',
                rating: 4.8,
                reviews: 324,
                price: 35.2,
                originalPrice: 42.0,
                discount: 16,
                location: 'Chiang Mai',
                duration: '6 hours',
                guide: 'Local guide',
                category: 'midrange',
                description: 'Trek through lush mountains and visit hill tribe villages',
                availableDates: [new Date(2025, 6, 29), new Date(2025, 6, 30)],
            },
            {
                id: 5,
                slug: "thailand-river-kayaking",
                title: 'Bangkok Food Street Walking Tour',
                image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400&h=300&fit=crop&crop=center',
                rating: 4.6,
                reviews: 678,
                bookings: '4K+',
                price: 28.99,
                location: 'Bangkok',
                duration: '3 hours',
                guide: 'Food expert guide',
                category: 'budget',
                description: 'Taste authentic street food and learn about Thai culinary culture',
                availableDates: [new Date(2025, 6, 28), new Date(2025, 6, 29)],
            },
            {
                id: 6,
                slug: "bangkok-food-night-market-tour",
                title: 'Pattaya Floating Market Day Trip',
                image: '/images/floating-market.jpg',
                rating: 4.4,
                reviews: 543,
                bookings: '2.5K+',
                price: 32.5,
                location: 'Pattaya',
                duration: 'Full day',
                guide: 'English guide',
                category: 'midrange',
                description: 'Experience traditional Thai floating market culture',
                availableDates: [new Date(2025, 6, 28), new Date(2025, 6, 30)],
            },
        ],
    },

    'massages-and-spa': {
        title: 'Massages & Spa',
        activities: [
            {
                id: 7,
                slug: "massage-hyper-knife-shibuya",
                title: 'Massage & Hyper Knife Experience (Shibuya, Tokyo)',
                image: '/images/massage1.jpeg',
                rating: 4.9,
                reviews: 235,
                bookings: '3K+',
                price: 24.79,
                originalPrice: 30.99,
                discount: 20,
                guide: 'English guide',
                description: 'Book now for tomorrow',
                availableDates: [new Date(2025, 6, 28), new Date(2025, 6, 29)],
            },
            {
                id: 8,
                slug: "onsen-ritual-hakone",
                title: 'Tokyo Relaxing Massage Nagomiya Omotesando Branch',
                image: '/images/massage2.jpeg',
                rating: 4.7,
                reviews: 892,
                price: 45.5,
                originalPrice: 55.0,
                discount: 17,
                location: 'Phuket',
                duration: '8 hours',
                guide: 'Multi-language guide',
                description: 'Free cancellation',
                availableDates: [new Date(2025, 6, 28), new Date(2025, 6, 30)],
            },
            {
                id: 9,
                slug: "thai-herbal-compress-massage",
                title: 'Tokyo Relaxing Massage Nagomiya Omotesando Branch',
                image: '/images/massage3.jpeg',
                rating: 4.3,
                reviews: 456,
                price: 15.99,
                location: 'Bangkok',
                duration: '24 hours',
                guide: 'Audio guide',
                description: "Book now for tomorrow",
                availableDates: [new Date(2025, 6, 28), new Date(2025, 6, 29)],
            },
            {
                id: 10,
                slug: "balinese-aromatherapy-session",
                title: 'Tokyo Relaxing Massage Nagomiya Omotesando Branch',
                image: '/images/massage4.jpeg',
                rating: 4.8,
                reviews: 324,
                price: 35.2,
                originalPrice: 42.0,
                discount: 16,
                location: 'Chiang Mai',
                duration: '6 hours',
                guide: 'Local guide',
                description: 'Free cancellation',
                availableDates: [new Date(2025, 6, 29), new Date(2025, 6, 30)],
            },
            {
                id: 11,
                slug: "tokyo-luxury-spa-day",
                title: 'Tokyo Relaxing Massage Nagomiya Omotesando Branch',
                image: '/images/massage5.jpeg',
                rating: 4.6,
                reviews: 678,
                bookings: '4K+',
                price: 28.99,
                location: 'Bangkok',
                duration: '3 hours',
                guide: 'Food expert guide',
                description: 'English guide  Private group',
                availableDates: [new Date(2025, 6, 28), new Date(2025, 6, 29)],
            },
            {
                id: 12,
                slug: "kyoto-zen-wellness-experience",
                title: 'Tokyo Relaxing Massage Nagomiya Omotesando Branch',
                image: '/images/massage6.jpeg',
                rating: 4.4,
                reviews: 543,
                bookings: '2.5K+',
                price: 32.5,
                location: 'Pattaya',
                duration: 'Full day',
                guide: 'English guide',
                description: 'English guide Afternoon departure',
                availableDates: [new Date(2025, 6, 28), new Date(2025, 6, 30)],
            },
        ],
    },
};